_target_: src.models.diffusion_module.DiffusionModule

in_size: 1024 # 32 x 32
t_range: 1000
img_depth: 1 # 1 for mnist and 3 for cifar
beta_small: 0.0001
beta_large:  0.02

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

compile: false